/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppMitreRouteImport } from './routes/_app.mitre'
import { Route as AppIncidentsRouteImport } from './routes/_app.incidents'
import { Route as AppEventsRouteImport } from './routes/_app.events'
import { Route as AppDetectionsRouteImport } from './routes/_app.detections'
import { Route as AppDetectionResultsRouteImport } from './routes/_app.detection-results'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAttackChainsRouteImport } from './routes/_app.attack-chains'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as AppIncidentsIndexRouteImport } from './routes/_app.incidents.index'
import { Route as AppAttackChainsIndexRouteImport } from './routes/_app.attack-chains.index'
import { Route as AppIncidentsIdRouteImport } from './routes/_app.incidents.$id'
import { Route as AppAttackChainsIdRouteImport } from './routes/_app.attack-chains.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMitreRoute = AppMitreRouteImport.update({
  id: '/mitre',
  path: '/mitre',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDetectionsRoute = AppDetectionsRouteImport.update({
  id: '/detections',
  path: '/detections',
  getParentRoute: () => AppRoute,
} as any)
const AppDetectionResultsRoute = AppDetectionResultsRouteImport.update({
  id: '/detection-results',
  path: '/detection-results',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAttackChainsRoute = AppAttackChainsRouteImport.update({
  id: '/attack-chains',
  path: '/attack-chains',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsIndexRoute = AppIncidentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIncidentsRoute,
} as any)
const AppAttackChainsIndexRoute = AppAttackChainsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAttackChainsRoute,
} as any)
const AppIncidentsIdRoute = AppIncidentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppIncidentsRoute,
} as any)
const AppAttackChainsIdRoute = AppAttackChainsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAttackChainsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/agents': typeof AppAgentsRoute
  '/alerts': typeof AppAlertsRoute
  '/attack-chains': typeof AppAttackChainsRouteWithChildren
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/detection-results': typeof AppDetectionResultsRoute
  '/detections': typeof AppDetectionsRoute
  '/events': typeof AppEventsRoute
  '/incidents': typeof AppIncidentsRouteWithChildren
  '/mitre': typeof AppMitreRoute
  '/settings': typeof AppSettingsRoute
  '/attack-chains/$id': typeof AppAttackChainsIdRoute
  '/incidents/$id': typeof AppIncidentsIdRoute
  '/attack-chains/': typeof AppAttackChainsIndexRoute
  '/incidents/': typeof AppIncidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/agents': typeof AppAgentsRoute
  '/alerts': typeof AppAlertsRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/detection-results': typeof AppDetectionResultsRoute
  '/detections': typeof AppDetectionsRoute
  '/events': typeof AppEventsRoute
  '/mitre': typeof AppMitreRoute
  '/settings': typeof AppSettingsRoute
  '/attack-chains/$id': typeof AppAttackChainsIdRoute
  '/incidents/$id': typeof AppIncidentsIdRoute
  '/attack-chains': typeof AppAttackChainsIndexRoute
  '/incidents': typeof AppIncidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/attack-chains': typeof AppAttackChainsRouteWithChildren
  '/_app/audit': typeof AppAuditRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/detection-results': typeof AppDetectionResultsRoute
  '/_app/detections': typeof AppDetectionsRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/incidents': typeof AppIncidentsRouteWithChildren
  '/_app/mitre': typeof AppMitreRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/attack-chains/$id': typeof AppAttackChainsIdRoute
  '/_app/incidents/$id': typeof AppIncidentsIdRoute
  '/_app/attack-chains/': typeof AppAttackChainsIndexRoute
  '/_app/incidents/': typeof AppIncidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/agents'
    | '/alerts'
    | '/attack-chains'
    | '/audit'
    | '/dashboard'
    | '/detection-results'
    | '/detections'
    | '/events'
    | '/incidents'
    | '/mitre'
    | '/settings'
    | '/attack-chains/$id'
    | '/incidents/$id'
    | '/attack-chains/'
    | '/incidents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/agents'
    | '/alerts'
    | '/audit'
    | '/dashboard'
    | '/detection-results'
    | '/detections'
    | '/events'
    | '/mitre'
    | '/settings'
    | '/attack-chains/$id'
    | '/incidents/$id'
    | '/attack-chains'
    | '/incidents'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/agents'
    | '/_app/alerts'
    | '/_app/attack-chains'
    | '/_app/audit'
    | '/_app/dashboard'
    | '/_app/detection-results'
    | '/_app/detections'
    | '/_app/events'
    | '/_app/incidents'
    | '/_app/mitre'
    | '/_app/settings'
    | '/_app/attack-chains/$id'
    | '/_app/incidents/$id'
    | '/_app/attack-chains/'
    | '/_app/incidents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mitre': {
      id: '/_app/mitre'
      path: '/mitre'
      fullPath: '/mitre'
      preLoaderRoute: typeof AppMitreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents': {
      id: '/_app/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detections': {
      id: '/_app/detections'
      path: '/detections'
      fullPath: '/detections'
      preLoaderRoute: typeof AppDetectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detection-results': {
      id: '/_app/detection-results'
      path: '/detection-results'
      fullPath: '/detection-results'
      preLoaderRoute: typeof AppDetectionResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attack-chains': {
      id: '/_app/attack-chains'
      path: '/attack-chains'
      fullPath: '/attack-chains'
      preLoaderRoute: typeof AppAttackChainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents/': {
      id: '/_app/incidents/'
      path: '/'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AppIncidentsIndexRouteImport
      parentRoute: typeof AppIncidentsRoute
    }
    '/_app/attack-chains/': {
      id: '/_app/attack-chains/'
      path: '/'
      fullPath: '/attack-chains/'
      preLoaderRoute: typeof AppAttackChainsIndexRouteImport
      parentRoute: typeof AppAttackChainsRoute
    }
    '/_app/incidents/$id': {
      id: '/_app/incidents/$id'
      path: '/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof AppIncidentsIdRouteImport
      parentRoute: typeof AppIncidentsRoute
    }
    '/_app/attack-chains/$id': {
      id: '/_app/attack-chains/$id'
      path: '/$id'
      fullPath: '/attack-chains/$id'
      preLoaderRoute: typeof AppAttackChainsIdRouteImport
      parentRoute: typeof AppAttackChainsRoute
    }
  }
}

interface AppAttackChainsRouteChildren {
  AppAttackChainsIdRoute: typeof AppAttackChainsIdRoute
  AppAttackChainsIndexRoute: typeof AppAttackChainsIndexRoute
}

const AppAttackChainsRouteChildren: AppAttackChainsRouteChildren = {
  AppAttackChainsIdRoute: AppAttackChainsIdRoute,
  AppAttackChainsIndexRoute: AppAttackChainsIndexRoute,
}

const AppAttackChainsRouteWithChildren = AppAttackChainsRoute._addFileChildren(
  AppAttackChainsRouteChildren,
)

interface AppIncidentsRouteChildren {
  AppIncidentsIdRoute: typeof AppIncidentsIdRoute
  AppIncidentsIndexRoute: typeof AppIncidentsIndexRoute
}

const AppIncidentsRouteChildren: AppIncidentsRouteChildren = {
  AppIncidentsIdRoute: AppIncidentsIdRoute,
  AppIncidentsIndexRoute: AppIncidentsIndexRoute,
}

const AppIncidentsRouteWithChildren = AppIncidentsRoute._addFileChildren(
  AppIncidentsRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAttackChainsRoute: typeof AppAttackChainsRouteWithChildren
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDetectionResultsRoute: typeof AppDetectionResultsRoute
  AppDetectionsRoute: typeof AppDetectionsRoute
  AppEventsRoute: typeof AppEventsRoute
  AppIncidentsRoute: typeof AppIncidentsRouteWithChildren
  AppMitreRoute: typeof AppMitreRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAttackChainsRoute: AppAttackChainsRouteWithChildren,
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDetectionResultsRoute: AppDetectionResultsRoute,
  AppDetectionsRoute: AppDetectionsRoute,
  AppEventsRoute: AppEventsRoute,
  AppIncidentsRoute: AppIncidentsRouteWithChildren,
  AppMitreRoute: AppMitreRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
